import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from levelupdiag_core.vcs import snapshot_tracked_files, restore_tracked_files


class VcsTests(unittest.TestCase):
    def test_restore_preserves_exact_pre_campaign_bytes(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / '.git').mkdir()
            file = root / 'apps/web/next-env.d.ts'
            file.parent.mkdir(parents=True)
            file.write_bytes(b'user baseline\r\n')
            tracked = {'exit_code': 0, 'stdout_tail': 'apps/web/next-env.d.ts\n'}
            with patch('levelupdiag_core.vcs.which', return_value='git'), \
                 patch('levelupdiag_core.vcs.run_command', return_value=tracked):
                snapshot = snapshot_tracked_files(root, ['apps/web/next-env.d.ts'])
            file.write_bytes(b'generated by next build\n')
            restored = restore_tracked_files(root, snapshot)
            self.assertEqual(restored, ['apps/web/next-env.d.ts'])
            self.assertEqual(file.read_bytes(), b'user baseline\r\n')

    def test_snapshot_rejects_escape_path(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / '.git').mkdir()
            with patch('levelupdiag_core.vcs.which', return_value='git'):
                with self.assertRaisesRegex(ValueError, 'inside the target repository'):
                    snapshot_tracked_files(root, ['../escape.txt'])

    def test_untracked_file_is_not_snapshotted(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / '.git').mkdir()
            file = root / 'apps/web/next-env.d.ts'
            file.parent.mkdir(parents=True)
            file.write_text('content')
            untracked = {'exit_code': 1, 'stdout_tail': ''}
            with patch('levelupdiag_core.vcs.which', return_value='git'), \
                 patch('levelupdiag_core.vcs.run_command', return_value=untracked):
                self.assertEqual(snapshot_tracked_files(root, ['apps/web/next-env.d.ts']), {})
